/* Generated by Cython 0.28.3 */

#ifndef __PYX_HAVE__hafnian__rlhafnian
#define __PYX_HAVE__hafnian__rlhafnian


#ifndef __PYX_HAVE_API__hafnian__rlhafnian

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void evals(double *, __pyx_t_double_complex *, int, double *, double *, int, double *);
__PYX_EXTERN_C PY_LONG_LONG haf_int(__Pyx_memviewslice, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__hafnian__rlhafnian */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initrlhafnian(void);
#else
PyMODINIT_FUNC PyInit_rlhafnian(void);
#endif

#endif /* !__PYX_HAVE__hafnian__rlhafnian */
