/* Generated by Cython 0.28.3 */

#ifndef __PYX_HAVE__librhaf
#define __PYX_HAVE__librhaf


#ifndef __PYX_HAVE_API__librhaf

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void evals(double *, __pyx_t_double_complex *, int, double *, double *, int, double *);

#endif /* !__PYX_HAVE_API__librhaf */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initlibrhaf(void);
#else
PyMODINIT_FUNC PyInit_librhaf(void);
#endif

#endif /* !__PYX_HAVE__librhaf */
