name: Formatting check
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run:
            python -m pip install --upgrade pip
            pip install black

      - uses: actions/checkout@v2

      - name: Run Black
        run: black -l 100 thewalrus/ --check
