name: Wheels MacOS
on:
  push:
    branches:
      - master
  pull_request:

env:
  CIBW_BUILD: 'cp37-* cp38-* cp39-*'

  # MacOS specific build settings
  CIBW_BEFORE_ALL_MACOS: |
    brew install gmp gcc libomp;

  # Python build settings
  CIBW_BEFORE_BUILD: |
    pip install numpy==1.19.5 scipy cython

  # Testing of built wheels
  CIBW_TEST_REQUIRES: numpy scipy pytest pytest-cov pytest-randomly flaky

  CIBW_TEST_COMMAND: |
    python -m pytest --randomly-seed=137 {project}/thewalrus

  CIBW_BUILD_VERBOSITY: 1

jobs:
  mac-wheels-x86:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        arch: [x86_64]
    name: ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.12.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: ${{matrix.arch}}

      - uses: kittaakos/upload-artifact-as-is@v0
        if: github.ref == 'refs/heads/master'
        with:
          path: ./wheelhouse/
